spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false
    username: root
    password: Dip4rudp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect